package de.craftery.autogenerated;

import de.craftery.autogenerated.listener.OnEnchant3;
import de.craftery.autogenerated.listener.OnEnchantPrepare2;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin {
    private static Main instance;

    @Override
    public void onEnable() {
        instance = this;
        new OnEnchantPrepare2();
        new OnEnchant3();
    }
    
    @Override
    public void onDisable() {
    }
    
    public static Main getInstance() {
        return instance;
    }
    
    public static void registerEvent(Listener event) {
        Main.getInstance().getServer().getPluginManager().registerEvents(event, Main.getInstance());
    }
    
}

