package de.craftery.autogenerated.listener;

import de.craftery.autogenerated.Main;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.enchantment.EnchantItemEvent;

public class OnEnchant3 implements Listener {
    public OnEnchant3() {
        Main.registerEvent(this);
    }
    
    @EventHandler
    public void onEnchant(EnchantItemEvent event) {
        Player player = event.getEnchanter();
        if (player.isOp()) {
            return;
        }
        else {
            event.setCancelled(true);
        }
    }
    
}

