package de.craftery.autogenerated;

import de.craftery.autogenerated.command.RankCommand;
import java.util.HashMap;
import java.util.Map;
import org.bukkit.Bukkit;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin {
    private static Main instance;
    private static final Map<String, Object> variableStore = new HashMap<>();

    @Override
    public void onEnable() {
        instance = this;
        PluginCommand rankCommand = Bukkit.getPluginCommand("rank");
        if (rankCommand != null) {
            rankCommand.setExecutor(new RankCommand());
        }
    }
    
    @Override
    public void onDisable() {
        PluginCommand rankCommand = Bukkit.getPluginCommand("rank");
        if (rankCommand != null) {
            rankCommand.setExecutor(null);
        }
    }
    
    public static Main getInstance() {
        return instance;
    }
    
    public static void setVariable(String key, Object value) {
        variableStore.put(key, value);
    }
    
    public static Object getVariable(String key) {
        return variableStore.get(key);
    }
    
    public static void deleteVariable(String key) {
        variableStore.remove(key);
    }
    
}

