package de.craftery.autogenerated.command;

import net.kyori.adventure.text.Component;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class OddsCommand implements CommandExecutor {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("§cThis command is only for players!");
            return true;
        }
        Player player = (Player) sender;
        
        if (args.length > 0) {
            sender.sendMessage("Correct usage: /odd");
            return true;
        }
        
        player.sendMessage(Component.text("§6§m§l------------------------"));
        player.sendMessage(Component.text("§4§lForgotten §8§l» §70.001%%."));
        player.sendMessage(Component.text("§d§lMythical §8§l» §70.1%%."));
        player.sendMessage(Component.text("§e§lGodly §8§l» §71%%."));
        player.sendMessage(Component.text("§6§lLegendary §8§l» §75%%."));
        player.sendMessage(Component.text("§5§lEpic §8§l» §710%%."));
        player.sendMessage(Component.text("§3§lRare §8§l» §725%%."));
        player.sendMessage(Component.text("§f§lCommon §8§l» §750%%"));
        player.sendMessage(Component.text("§a§lTrash §8§l» §710%%"));
        player.sendMessage(Component.text("§eTag(s) §8§l» §71%%"));
        player.sendMessage(Component.text("§cBoss §8§l» §75%%"));
        player.sendMessage(Component.text("§2Key(s) §8§l» §71%%"));
        player.sendMessage(Component.text("§6§m§l------------------------"));
        return true;
    }
    
}

