package de.craftery.autogenerated.command;

import java.util.List;
import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;

public class AcCommand implements CommandExecutor {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("§cThis command is only for players!");
            return true;
        }
        Player player = (Player) sender;
        
        if (args.length > 0) {
            sender.sendMessage("Correct usage: /ac");
            return true;
        }
        
        ItemStack itemStack15 = new ItemStack(Material.PAPER, 1);
        itemStack15.getItemMeta().displayName(Component.text("§r§6§lWheat §f§lCompressor"));
        itemStack15.getItemMeta().lore(List.of(Component.text("§6Compresses Wheat For You Right Click to Redeem")));
        player.getInventory().addItem(itemStack15);
        ItemStack itemStack16 = new ItemStack(Material.PAPER, 1);
        itemStack16.getItemMeta().displayName(Component.text("§r§9§lCarrot §f§lCompressor"));
        itemStack16.getItemMeta().lore(List.of(Component.text("§9Compresses Carrot's For You Right Click to Redeem")));
        player.getInventory().addItem(itemStack16);
        ItemStack itemStack17 = new ItemStack(Material.PAPER, 1);
        itemStack17.getItemMeta().displayName(Component.text("§r§4§lPotato §r§f§lCompressor"));
        itemStack17.getItemMeta().lore(List.of(Component.text("§4Compresses Carrot's For You Right Click to Redeem")));
        player.getInventory().addItem(itemStack17);
        ItemStack itemStack18 = new ItemStack(Material.PAPER, 1);
        itemStack18.getItemMeta().displayName(Component.text("§r§a§lBeetroot §r§f§lCompressor"));
        itemStack18.getItemMeta().lore(List.of(Component.text("§aCompresses Carrot's For You Right Click to Redeem")));
        player.getInventory().addItem(itemStack18);
        return true;
    }
    
}

