package de.craftery.autogenerated.listener;

import de.craftery.autogenerated.Main;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.ItemStack;

public class OnClick2 implements Listener {
    public OnClick2() {
        Main.registerEvent(this);
    }
    
    @EventHandler
    public void onClick(PlayerInteractEvent event) {
        Player player = event.getPlayer();
        if (event.getAction() != Action.RIGHT_CLICK_BLOCK && event.getAction() != Action.RIGHT_CLICK_AIR) {
            return;
        }
        
        if (player.getInventory().getItemInMainHand().getType() == Material.PAPER && ((TextComponent) player.getInventory().getItemInMainHand().getItemMeta().displayName()).content() == "§r§6§lWheat §f§lCompressor" && player.getInventory().getItemInMainHand().getItemMeta().lore().stream().anyMatch(el3 -> ((TextComponent) el3).content() == "§6Compresses Wheat For You Right Click to Redeem")) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "/lp user " + player.getName() + " permission set command.ac");
            for (ItemStack item4 : player.getInventory().getContents()) {
                if (item4.getAmount() == 1 && item4.getType() == Material.PAPER && ((TextComponent) item4.getItemMeta().displayName()).content() == "§r§6§lWheat §f§lCompressor" && item4.getItemMeta().lore().stream().anyMatch(el5 -> ((TextComponent) el5).content() == "§6Compresses Wheat For You Right Click to Redeem")) {
                    player.getInventory().removeItem(item4);
                }
            }
            player.sendMessage(Component.text("§6§lAutoCompressor§7: §f§lWheat Unlocked!"));
        }
        else if (player.getInventory().getItemInMainHand().getType() == Material.PAPER && ((TextComponent) player.getInventory().getItemInMainHand().getItemMeta().displayName()).content() == "§r§9§lCarrot §f§lCompressor" && player.getInventory().getItemInMainHand().getItemMeta().lore().stream().anyMatch(el6 -> ((TextComponent) el6).content() == "§9Compresses Carrot's For You Right Click to Redeem")) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "/lp user " + player.getName() + " permission set command.ac2");
            for (ItemStack item7 : player.getInventory().getContents()) {
                if (item7.getAmount() == 1 && item7.getType() == Material.PAPER && ((TextComponent) item7.getItemMeta().displayName()).content() == "§r§9§lCarrot §f§lCompressor" && item7.getItemMeta().lore().stream().anyMatch(el8 -> ((TextComponent) el8).content() == "§9Compresses Carrot's For You Right Click to Redeem")) {
                    player.getInventory().removeItem(item7);
                }
            }
            player.sendMessage(Component.text("§9§lAutoCompressor§7: §f§lCarrot unlocked!"));
        }
        else if (player.getInventory().getItemInMainHand().getType() == Material.PAPER && ((TextComponent) player.getInventory().getItemInMainHand().getItemMeta().displayName()).content() == "§r§4§lPotato §r§f§lCompressor" && player.getInventory().getItemInMainHand().getItemMeta().lore().stream().anyMatch(el9 -> ((TextComponent) el9).content() == "§4Compresses Carrot's For You Right Click to Redeem")) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "/lp user " + player.getName() + " permission set command.ac3");
            for (ItemStack item10 : player.getInventory().getContents()) {
                if (item10.getAmount() == 1 && item10.getType() == Material.PAPER && ((TextComponent) item10.getItemMeta().displayName()).content() == "§r§4§lPotato §r§f§lCompressor" && item10.getItemMeta().lore().stream().anyMatch(el11 -> ((TextComponent) el11).content() == "§4Compresses Carrot's For You Right Click to Redeem")) {
                    player.getInventory().removeItem(item10);
                }
            }
            player.sendMessage(Component.text("§4§lAutoCompressor§7: §f§lPotato unlocked!"));
        }
        else if (player.getInventory().getItemInMainHand().getType() == Material.PAPER && ((TextComponent) player.getInventory().getItemInMainHand().getItemMeta().displayName()).content() == "§r§a§lBeetroot §r§f§lCompressor" && player.getInventory().getItemInMainHand().getItemMeta().lore().stream().anyMatch(el12 -> ((TextComponent) el12).content() == "§aCompresses Carrot's For You Right Click to Redeem")) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "/lp user " + player.getName() + " permission set command.ac4");
            for (ItemStack item13 : player.getInventory().getContents()) {
                if (item13.getAmount() == 1 && item13.getType() == Material.PAPER && ((TextComponent) item13.getItemMeta().displayName()).content() == "§r§a§lBeetroot §r§f§lCompressor" && item13.getItemMeta().lore().stream().anyMatch(el14 -> ((TextComponent) el14).content() == "§aCompresses Carrot's For You Right Click to Redeem")) {
                    player.getInventory().removeItem(item13);
                }
            }
            player.sendMessage(Component.text("§a§lAutoCompressor§7: §f§lBeetroot unlocked!"));
        }
    }
    
}

