package de.craftery.autogenerated;

import de.craftery.autogenerated.command.AcCommand;
import de.craftery.autogenerated.listener.OnClick2;
import org.bukkit.Bukkit;
import org.bukkit.command.PluginCommand;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin {
    private static Main instance;

    @Override
    public void onEnable() {
        instance = this;
        new OnClick2();
        PluginCommand acCommand = Bukkit.getPluginCommand("ac");
        if (acCommand != null) {
            acCommand.setExecutor(new AcCommand());
        }
    }
    
    @Override
    public void onDisable() {
        PluginCommand acCommand = Bukkit.getPluginCommand("ac");
        if (acCommand != null) {
            acCommand.setExecutor(null);
        }
    }
    
    public static Main getInstance() {
        return instance;
    }
    
    public static void registerEvent(Listener event) {
        Main.getInstance().getServer().getPluginManager().registerEvents(event, Main.getInstance());
    }
    
}

