package de.craftery.autogenerated.listener;

import de.craftery.autogenerated.Main;
import io.papermc.paper.event.player.AsyncChatEvent;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class OnChat2 implements Listener {
    public OnChat2() {
        Main.registerEvent(this);
    }
    
    @EventHandler
    public void onChat(AsyncChatEvent event) {
        Player player = event.getPlayer();
        if (Main.getVariable("rank." + player.getName() + "") == "§4§lOWNER§4") {
            Main.setVariable("sort." + player.getName() + "", " §0§r");
        }
        if (Main.getVariable("rank." + player.getName() + "") == "§c§lADMIN§c") {
            Main.setVariable("sort." + player.getName() + "", " §1§r");
        }
        if (Main.getVariable("rank." + player.getName() + "") == "§e§lMOD§e") {
            Main.setVariable("sort." + player.getName() + "", " §2§r");
        }
        if (Main.getVariable("rank." + player.getName() + "") == "§b§lHELPER§b") {
            Main.setVariable("sort." + player.getName() + "", " §d§r");
        }
        if (Main.getVariable("rank." + player.getName() + "") == "§7") {
            Main.setVariable("sort." + player.getName() + "", " §e§r");
        }
    }
    
}

