package de.craftery.autogenerated.command;

import de.craftery.autogenerated.Main;
import net.kyori.adventure.text.Component;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class RankCommand implements CommandExecutor {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("§cThis command is only for players!");
            return true;
        }
        Player player = (Player) sender;
        
        String argument1 = args[0];
        String argument2 = args[1];
        StringBuilder argumentBuilder = new StringBuilder();
        for (int i = 2; i < args.length; i++) {
            argumentBuilder.append(args[i]);
            if (i != args.length) argumentBuilder.append(" ");
        }
        String argument3 = argumentBuilder.toString();
        
        if (argument1 == null) {
            player.sendMessage(Component.text("§6§m§l--------------------------------------------------"));
            player.sendMessage(Component.text("§e/rank set (player) (rank) §8» §7Sets a player's rank."));
            player.sendMessage(Component.text("§e/rank list §8» §7Shows a list of all the groups on the server."));
            player.sendMessage(Component.text("§e/rank info §8» §7Shows info about the Skript."));
            player.sendMessage(Component.text("§6§m§l--------------------------------------------------"));
        }
        else if (argument1 == "set") {
            if (argument2 != null) {
                if (argument3 == "Administrator" || argument3 == "Admin") {
                    Main.setVariable("rank." + argument2 + "", " §c§lADMIN§c");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §c§lADMIN§7."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §c§lADMIN§7."));
                }
                if (argument3 == "Mod" || argument3 == "Moderator") {
                    Main.setVariable("rank." + argument2 + "", " §e§lMOD§e");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §e§lMOD§7."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §e§lMOD§7."));
                }
                if (argument3 == "Helper" || argument3 == "Support") {
                    Main.setVariable("rank." + argument2 + "", " §b§lHELPER§b");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §b§lHELPER§7."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §b§lHELPER§7."));
                }
                if (argument3 == "Owner") {
                    Main.setVariable("rank." + argument2 + "", " §4§lOWNER§4");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §4§lOWNER§7."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §4§lOWNER§7."));
                }
                if (argument3 == "default") {
                    Main.setVariable("rank." + argument2 + "", " §7");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §7default."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §7default."));
                }
                if (argument3 == "builder") {
                    Main.setVariable("rank." + argument2 + "", " §9§lBUILDER");
                    player.sendMessage(Component.text("§6§lRANKS §8| §e" + argument2 + "'s §7rank is now to set to §9§lBUILDER."));
                    Bukkit.getPlayer(argument2).sendMessage(Component.text("§6§lRANKS §8| §7Your rank has been set to §9§lBUILDER."));
                }
                if (argument3 != "default" || argument3 != "Helper" || argument3 != "Support" || argument3 != "Moderator" || argument3 != "Mod" || argument3 != "Admin" || argument3 != "Owner" || argument3 != "builder" || argument3 != "Administrator") {
                    player.sendMessage(Component.text("§6§lRANKS §8| §7That is not a role. Do §e/rank list §7to see the roles available."));
                }
            }
            else {
                player.sendMessage(Component.text("§6§lRANKS §8| §7Please specify a user to set the rank for."));
            }
        }
        else if (argument1 == "list") {
            player.sendMessage(Component.text("§6§m§l--------------------------------------------------"));
            player.sendMessage(Component.text("§4§lOWNER §8§l» §7Has every permission."));
            player.sendMessage(Component.text("§c§lADMIN §8§l» §7Has every permission."));
            player.sendMessage(Component.text("§6§lSR.MOD §8§l» §7Has every permission."));
            player.sendMessage(Component.text("§c§lMOD §8§l» §7Has punishment and gamemode permissions."));
            player.sendMessage(Component.text("§b§lHELPER §8§l» §7Has kick and fly permissions."));
            player.sendMessage(Component.text("§7default §8§l» §7Not much."));
            player.sendMessage(Component.text("§6§m§l--------------------------------------------------"));
        }
        return true;
    }
    
}

