package de.craftery.autogenerated.command;

import de.craftery.autogenerated.Formatter;
import de.craftery.autogenerated.Main;
import net.kyori.adventure.text.Component;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class SetspawnCommand implements CommandExecutor {
    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (!(sender instanceof Player)) {
            sender.sendMessage("§cThis command is only for players!");
            return true;
        }
        Player player = (Player) sender;
        
        if (args.length > 0) {
            sender.sendMessage("Correct usage: /setspawn");
            return true;
        }
        
        Main.setVariable("spawn", player.getLocation().getBlock().getLocation());
        player.sendMessage(Component.text("Set Spawn Location to " + Formatter.formatUnknown(Main.getVariable("spawn")) + ""));
        return true;
    }
    
}

