package de.craftery.autogenerated;

import de.craftery.autogenerated.command.SorterCommand;
import de.craftery.autogenerated.listener.OnChat2;
import java.util.HashMap;
import java.util.Map;
import org.bukkit.Bukkit;
import org.bukkit.command.PluginCommand;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin {
    private static Main instance;
    private static final Map<String, Object> variableStore = new HashMap<>();

    @Override
    public void onEnable() {
        instance = this;
        new OnChat2();
        PluginCommand sorterCommand = Bukkit.getPluginCommand("sorter");
        if (sorterCommand != null) {
            sorterCommand.setExecutor(new SorterCommand());
        }
    }
    
    @Override
    public void onDisable() {
        PluginCommand sorterCommand = Bukkit.getPluginCommand("sorter");
        if (sorterCommand != null) {
            sorterCommand.setExecutor(null);
        }
    }
    
    public static Main getInstance() {
        return instance;
    }
    
    public static void setVariable(String key, Object value) {
        variableStore.put(key, value);
    }
    
    public static Object getVariable(String key) {
        return variableStore.get(key);
    }
    
    public static void deleteVariable(String key) {
        variableStore.remove(key);
    }
    
    public static void registerEvent(Listener event) {
        Main.getInstance().getServer().getPluginManager().registerEvents(event, Main.getInstance());
    }
    
}

