package de.craftery.autogenerated.listener;

import de.craftery.autogenerated.Main;
import org.bukkit.entity.Entity;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEntityEvent;
import org.bukkit.inventory.EquipmentSlot;

public class OnClick19 implements Listener {
    public OnClick19() {
        Main.registerEvent(this);
    }
    
    @EventHandler
    public void onClick(PlayerInteractEntityEvent event) {
        Player player = event.getPlayer();
        Entity entity = event.getRightClicked();
        if (event.getHand() != EquipmentSlot.HAND) {
            return;
        }
        
        if (entity.getName() == "§9§lHerbert") {
            if (player.isOp()) {
                return;
            }
            else if (!player.isOp()) {
                event.setCancelled(true);
            }
        }
        else if (entity.getName() == "§9§lGünther" || entity.getName() == "§9§lKlaus" || entity.getName() == "§9§lDieter" || entity.getName() == "§9§lWolfgang" || entity.getName() == "§9§lPeter" || entity.getName() == "§9§lHartmut" || entity.getName() == "§9§lEdgar") {
            return;
        }
        else if (entity.getType() == EntityType.VILLAGER) {
            if (!player.isOp()) {
                event.setCancelled(true);
            }
        }
    }
    
}

