package de.craftery.writer.core;

import de.craftery.writer.WritingSection;

import java.util.ArrayList;
import java.util.List;

public class PluginYMLHeader extends WritingSection {
    public PluginYMLHeader() {
        super(0);
    }

    private final List<String> dependencies = new ArrayList<>();

    public void requireDependency(String dependency) {
        if (!dependencies.contains(dependency)) {
            dependencies.add(dependency);
        }
    }

    @Override
    public void buildLines() {
        this.getLines().add("name: \"AutogeneratedPlugin\"");
        this.getLines().add("version: \"${project.version}\"");
        this.getLines().add("main: \"de.craftery.autogenerated.Main\"");
        this.getLines().add("api-version: \"1.18\"");
        this.getLines().add("api: [ \"1.18\" ]");
        this.getLines().add("authors: [ \"Nobody\" ]");
        this.getLines().add("prefix: \"AutogeneratedPlugin\"");
        this.getLines().add("website: \"https://github.com/Crafter-Y/SkriptLang-Compiler/\"");
        if (dependencies.size() != 0) {
            this.getLines().add("depend:");
            for (String dependency : dependencies) {
                this.getLines().add("  - " + dependency);
            }
        }
        this.getLines().add("");
    }
}
