package de.craftery.writer.actions.events;

import de.craftery.Main;
import de.craftery.writer.actions.ActionGenerator;
import de.craftery.writer.core.MainGenerator;
import de.craftery.writer.javaFile.ClassSection;
import de.craftery.writer.javaFile.RawMethodSection;

public class PlayerInteractEntityEventGenerator extends ActionGenerator {
    private final RawMethodSection bodyPart;
    private boolean rightClickRequired = false;

    // https://skripthub.net/docs/?id=4262
    public PlayerInteractEntityEventGenerator() {
        this.setPackage("listener");
        this.setNeeded(true);

        int moduleInt = Main.nextModuleInt();
        String moduleName = "OnClick" + moduleInt;
        this.setFileName(moduleName);
        ClassSection classSection = new ClassSection(0);
        classSection.setClassName(moduleName);
        classSection.addImplementationClass("Listener");

        RawMethodSection constructor = new RawMethodSection(1);
        constructor.setRawMethodSignature("public OnClick"+ moduleInt +"()");
        constructor.addLine("Main.registerEvent(this);");

        classSection.addMethod(constructor);

        RawMethodSection methodSection = new RawMethodSection(1);
        methodSection.setRawMethodSignature("public void onClick(PlayerInteractEntityEvent event)");
        methodSection.addAnnotation("@EventHandler");
        methodSection.addLine("Player player = event.getPlayer();");
        methodSection.addLine("Entity entity = event.getRightClicked();");

        classSection.addMethod(methodSection);
        this.addClass(classSection);

        this.requireImport("org.bukkit.event.Listener");
        this.requireImport("org.bukkit.event.EventHandler");
        this.requireImport("org.bukkit.event.player.PlayerInteractEntityEvent");
        this.requireImport("de.craftery.autogenerated.Main");
        this.requireImport("org.bukkit.entity.Player");
        this.requireImport("org.bukkit.entity.Entity");

        MainGenerator.registerEvent(moduleName);

        bodyPart = this.getClasses().get(0).getMethods().get(1);
    }

    @Override
    public void build() {
        RawMethodSection bodyPart = this.bodyPart;

        if (rightClickRequired) {
            bodyPart.addLine("if (event.getHand() != EquipmentSlot.HAND) {");
            bodyPart.addLine("    return;");
            bodyPart.addLine("}");
            bodyPart.addLine("");

            this.requireImport("org.bukkit.inventory.EquipmentSlot");
        }

        super.build();
    }

    @Override
    public void setOnlyExecutableByPlayers() {}

    @Override
    public void requireRightClick() {
        rightClickRequired = true;
    }

    @Override
    public Type getType() {
        return Type.PREPARE_ENCHANT_EVENT;
    }

    @Override
    protected RawMethodSection getBodySection() {
        return bodyPart;
    }
}
