package de.craftery.writer.actions.events;

import de.craftery.Main;
import de.craftery.writer.actions.ActionGenerator;
import de.craftery.writer.core.MainGenerator;
import de.craftery.writer.javaFile.ClassSection;
import de.craftery.writer.javaFile.RawMethodSection;

public class PrepareItemEnchantGenerator extends ActionGenerator {
    private final RawMethodSection bodyPart;
    public PrepareItemEnchantGenerator() {
        this.setPackage("listener");
        this.setNeeded(true);

        int moduleInt = Main.nextModuleInt();
        String moduleName = "OnEnchantPrepare" + moduleInt;
        this.setFileName(moduleName);
        ClassSection classSection = new ClassSection(0);
        classSection.setClassName(moduleName);
        classSection.addImplementationClass("Listener");

        RawMethodSection constructor = new RawMethodSection(1);
        constructor.setRawMethodSignature("public OnEnchantPrepare"+ moduleInt +"()");
        constructor.addLine("Main.registerEvent(this);");

        classSection.addMethod(constructor);

        RawMethodSection methodSection = new RawMethodSection(1);
        methodSection.setRawMethodSignature("public void onEnchantPrepare(PrepareItemEnchantEvent event)");
        methodSection.addAnnotation("@EventHandler");
        methodSection.addLine("Player player = event.getEnchanter();");

        classSection.addMethod(methodSection);
        this.addClass(classSection);

        this.requireImport("org.bukkit.event.Listener");
        this.requireImport("org.bukkit.event.EventHandler");
        this.requireImport("org.bukkit.event.enchantment.PrepareItemEnchantEvent");
        this.requireImport("de.craftery.autogenerated.Main");
        this.requireImport("org.bukkit.entity.Player");

        MainGenerator.registerEvent(moduleName);

        bodyPart = this.getClasses().get(0).getMethods().get(1);
    }

    @Override
    public void setOnlyExecutableByPlayers() {}

    @Override
    public Type getType() {
        return Type.PREPARE_ENCHANT_EVENT;
    }

    @Override
    protected RawMethodSection getBodySection() {
        return bodyPart;
    }
}
