package de.craftery.writer;

public class JavaFileGenerator extends WriterComponent {
    @Override
    public void prepareContent() {

    }

    public JavaFileGenerator() {
        this.setPackagePrefix("de.craftery.autogenerated");
    }

    @Override
    public void setFileName(String fileName) {
        super.setFileName(fileName + ".java");
    }

}
